services:

  api:

    build:
      context: .
      dockerfile: docker/python/Dockerfile

    container_name: webinar_api

    restart: unless-stopped

    volumes:
      - .:/app

    env_file:
      - .env

    depends_on:
      - mysql

    networks:
      - webinar-network


  mysql:

    image: mysql:8.4

    container_name: webinar_mysql

    restart: unless-stopped

    ports:
      - "3307:3306"

    environment:

      MYSQL_ROOT_PASSWORD: root123

      MYSQL_DATABASE: webinar_management

      MYSQL_USER: didi

      MYSQL_PASSWORD: didi123

    volumes:

      - mysql_data:/var/lib/mysql

    networks:

      - webinar-network


  nginx:

    image: nginx:alpine

    container_name: webinar_nginx

    restart: unless-stopped

    ports:

      - "8000:80"

    volumes:

      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

    depends_on:

      - api

    networks:

      - webinar-network


volumes:

  mysql_data:


networks:

  webinar-network:
