services:

  api:

    image: riyadirevolver/webinar-management-api:latest

    container_name: webinar_api

    restart: unless-stopped

    env_file:
      - .env

    depends_on:
      mysql:
        condition: service_healthy

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s

    networks:
      - webinar-network


  mysql:

    image: mysql:8.4

    container_name: webinar_mysql

    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: webinar_management
      MYSQL_USER: didi
      MYSQL_PASSWORD: didi123

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-uroot",
          "-proot123"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - webinar-network


  nginx:

    image: nginx:alpine

    container_name: webinar_nginx

    restart: unless-stopped

    ports:
      - "80:80"

    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

    depends_on:
      api:
        condition: service_healthy

    networks:
      - webinar-network


volumes:
  mysql_data:


networks:
  webinar-network:
    driver: bridge
